version: '3.8'
services:
  internal_rabbitmq:
    image: rabbitmq:3.9.5-management-alpine
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - rabbitmq_network
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password@vascobank123

networks:
  rabbitmq_network:
    driver: bridge
